### ISSUE TITLE
Rounds

### ISSUE THREAD

**Issue by Matocolotoe** [NiklasEi/mp-gamebundle-for-gamebox#3]
In the config of Rock Paper Scissors :
- when you set rounds to 5, there are only 3
- when you set them to 7, there are 4
- etc

**Comment by NiklasEi** [comment]
Five rounds in the config means best of 5. Meaning, that when one player wins 3 rounds he won the whole game. If you set it to 5 and win twice with both players, there should be a fifth round.

**Comment by Matocolotoe** [comment]
Ok ! Thank you :)
