### ISSUE TITLE
Add an option to config player skull names (TicTacToe 1v1)

### ISSUE THREAD

**Issue by Matocolotoe** [NiklasEi/mp-gamebundle-for-gamebox#5]
See title

**Comment by NiklasEi** [comment]
I am guessing you mean the heads in rock paper scissors?
That should work already since ef624bd. The message 'playerHeadName' in the language file is used as display name for the heads.

**Comment by Matocolotoe** [comment]
forgot to change that title xd @NiklasEi

**Comment by NiklasEi** [comment]
I misunderstood you here. Completely forgot, that there are also skulls in tic tac toe MP.
